; Ajustes de PHP para SCAFI
upload_max_filesize = 40M
post_max_size = 40M
; Algunos scripts se conectan con "localhost" (socket) en lugar de 127.0.0.1
mysqli.default_socket = /run/mysqld/mysqld.sock
pdo_mysql.default_socket = /run/mysqld/mysqld.sock
